# https://rust-lang.github.io/rustfmt/?version=v1.4.36&search=#normalize_doc_attributes
blank_lines_lower_bound         = 0
blank_lines_upper_bound         = 2  # Don't think i like the behaviour this intorudces
brace_style                     = "PreferSameLine"
condense_wildcard_suffixes      = true
control_brace_style             = "AlwaysSameLine"
edition                         = "2018"
empty_item_single_line          = false
enum_discrim_align_threshold    = 80
error_on_line_overflow          = true
error_on_unformatted            = true
fn_args_layout                  = "Tall"
fn_single_line                  = false
format_code_in_doc_comments     = true
format_strings                  = true
imports_granularity             = "Module"
imports_indent                  = "Block"
imports_layout                  = "Mixed"
indent_style                    = "Block"
# license_template_path           = "LICENSE"  TODO: how does this work?
match_arm_leading_pipes         = "Never"  # "Always"
max_width                       = 120
merge_derives                   = true
newline_style                   = "Unix"
normalize_comments              = true
normalize_doc_attributes        = true
reorder_impl_items              = true
reorder_imports                 = true
group_imports                   = "StdExternalCrate"
reorder_modules                 = true
space_after_colon               = true
space_before_colon              = false
spaces_around_ranges            = false
struct_field_align_threshold    = 0
struct_lit_single_line          = true
tab_spaces                      = 4
trailing_comma                  = "Vertical"
match_block_trailing_comma      = false
trailing_semicolon              = true
type_punctuation_density        = "Wide"
unstable_features               = true
use_field_init_shorthand        = true # As a note, this mixes the short-hand with normal
wrap_comments                   = true
overflow_delimited_expr         = true
